### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-wp2-data-dictionary#1]
@jpbacelar wrote:

> Dear Partners,
> 
> Please find bellow the link for the data dictionary that is available on dropbox. We look forward for your feedback until the 4th of July, as discussed minutes ago.
> 
> Dictionary: https://www.dropbox.com/s/0xlh2ly3ecw4ebq/2016_05_data_dictionary.xlsx?dl=0
> 
> Thanks in advance!
> Joao 

I have uploaded this version to GitHub too, for reference. This version was last changed by @pleys at 2016-06-20, with the SHA-1 checksum of 2fbd38a025d1c3b95c0f03f24f2e99af865a7b90. I have tagged it as version `1.0.0` in Git repository.

And here's some feedback :)
## General impression

Most of the terms seem to be consistent with the terms used by us (WP4) both internally, and in our API specifications. I feel comfortable with accepting this version of the document as the base for our vocabulary.
- We will try to keep all of our WP4's specifications in sync with this vocabulary.
- If a single entity has many names, we should use the "primary" name when providing the title for our objects, entities and XML elements, while keeping the alternate name in descriptions only (or, in case of specifications, in parentheses). This way, we will prevent inconsistencies across specifications.
- We hope that other WPs will also try to keep the same names in their specifications. E.g. in the model, and the elements in our XML files. This will make the "end product" look much more professional.
### IIA sheet
- `autumn_term` and `spring_term` fields will point to a specific date, not only a month, I think. Is `other_term` a text-field (with just a text description)?
- What are `visa_contact` and `visa_website` fields? Could you add some descriptions (just basic ones)?
### Some empty sheets?

Some sheets seem to be empty: Nominations, Arr&Dep date.
### Learning Agreement
- I believe that `nationality` should be replaced with `citizenship`.
- Does `gender` have only two possible values? This field is mandatory, so it seems important.

**Comment by wrygiel** [comment]
I have just remembered one more request...

Could you, perhaps, introduce a common term which would match the definition of "a single continuous period of mobility of a single student"?

We (WP4) have simply used "mobility" so far, whereas WP3 proposed "person-mobility". This entity will be a very important one throughout all of our specifications, so we will eventually need to pick one, and I believe it should find its way to WP2's vocabulary.

@jpbacelar, @StefanJahnke - Could you help?

**Comment by ghost** [comment]
@jbacelar, @StefanJahnke 

_learning agreement_
I think first name and last name of the student are missing in learning agreement (only email is mentioned).
_learning agreement changes_
Should we also include sending and receiving ECTS alternative?
Should we include the predefined reasons for change?
_IIA_
I am missing the G-section on signatures.

**Comment by StefanJahnke** [comment]
Hello everyone,
thanks for the initial feedback. I included some additional descriptions as requested.

I suggest using the term 'mobility'. It should be sufficiently clear what "a mobility" means throughout the project. I wouldn't argue against person-mobility either though.

_autumn_term_ and _spring_term_ are described as only the month of when the semester begins. I suppose that at an institution the exact date can differ between faculties and that's why the template suggest to have only a month here. Maybe an additional information such as "month in which the first course/programme starts". I am not sure if universities have an actual starting date with a precise day.

_nationality_ is the official description in the LA template and I kept it as nationality therefore. I know it is a debatable term but I'd rather follow the leader of the official template in this case.

_gender_ has strangely enough only the description of M/F in the LA template. I would for once suggest to deviate from the official template and include also the option of 'other'.

**Learning Agreement**
The first name and last name are included in the current version

Maybe a field for "ECTS alternative" could be added to the LA changes as well

How would you include the reason for change data? I imagine that it would have to be part rather of the description in the tool (or e.g. in the standard connector) at the university side. The _reasons for change_ as such is not data that needs to be transferred repeatedly, as it is static information. 

**IIA**
I indeed didn't include the signature information in the IIA in the initial version. It is now corrected.

**Arrival & Departure information**
I now added a simple set of data, which is a date. Depending if the information is delivered separately, a student identifier needs to be added as well or we once again need to add fields such as name, firstname, date of birth etc. to the set of data. I leave it up to the architecture gurus to think of how the identifier of the 'mobility' will work best

**Nominations**
I am a bit on the fence when it comes to nominations. There is clearly no template on European level how nominations are taking place and from the desk-research it becomes clear that there is a variety of different procedures and data that is being transferred. It can be as simple as information about the name and first name of a student and as complex as including an overview of grades and a range of personal information.

I would here rely on our colleagues from e.g. SOP to share their expertise on how to handle nominations and possibly add suggestions for data that we should consider as standard in the framework of EWP @georgschermann 

Nota Bene: I updated the file amended by Matija and called it _v3 in the dropbox
